name: BackendTests

on:
  pull_request:
    branches: main
    paths: 
      - "Cloud Functions/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # - name: Run linter
      #   run: deno lint

      - name: Run tests
        run: deno test -A --junit-path report.xml

      - name: Coverage report
        run: deno test -A --coverage=cov_profile ; deno coverage cov_profile --html

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml
          retention-days: 5

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cov_profile/html
          retention-days: 5